trigger:
  - master

variables:
- group: build.variables

pool:
  vmImage: "ubuntu-latest"

steps:
- task: Docker@2
  displayName: "Build & Push Docker Image"
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '$(dockerTag)'
